// components/src/preact/mutations/mutations-grid.tsx
import { FunctionComponent } from 'preact';
import { Row } from 'gridjs';
import { Dataset } from '../../operator/Dataset';
import { SequenceType } from '../../types';
import { bases } from '../../mutations';
import { DeletionEntry, MutationEntry, SubstitutionEntry } from '../../operator/FetchMutationsOperator';
import { Table, tableStyle } from '../components/table';

type MutationCell = {
    isReference: boolean;
    value: number;
};

type AdditionalColumnInfo = {
    isReference: boolean;
};

interface MutationsGridProps {
    data: Dataset<MutationEntry>;
    sequenceType: SequenceType;
}

export const MutationsGrid: FunctionComponent<MutationsGridProps> = ({ data, sequenceType }) => {
    const getHeaders = () => {
        return [
            {
                name: 'Position',
                sort: {
                    compare: (a: string, b: string) => {
                        return sortPositionsWithSegments(a, b);
                    },
                },
            },
            ...getBasesHeaders(),
        ];
    };

    const getBasesHeaders = () => {
        // This is a workaround, since gridjs does not support sorting of object cells in conjunction with the formatter
        // here each presented table cell is represented by two cells,
        // one for the value and one for the reference information

        const getAdditionalInfo = (columnIndex: number, row: Row) => {
            const numberOfNonBasesColumns = 1;
            return row.cell(numberOfNonBasesColumns + 1 + 2 * columnIndex).data as AdditionalColumnInfo;
        };

        return bases[sequenceType]
            .map((base, index) => {
                return [
                    {
                        name: base,
                        sort: true,
                        formatter: (cell: number) => formatProportion(cell),
                        attributes: (cell: number, row: Row) => {
                            // grid-js: the cell and row are null for header cells
                            if (row === null) {
                                return {};
                            }

                            return styleCells({
                                value: cell,
                                ...getAdditionalInfo(index, row),
                            });
                        },
                    },
                    { name: `additionalInfo for ${base}`, hidden: true },
                ];
            })
            .flat();
    };

    const sortPositionsWithSegments = (a: string, b: string) => {
        const split = (s: string) => {
            const parts = s.split(':');
            if (parts.length === 1) {
                return [undefined, parseInt(parts[0], 10)] as const;
            }
            return [parts[0], parseInt(parts[1], 10)] as const;
        };
        const [aSegment, aPosition] = split(a);
        const [bSegment, bPosition] = split(b);
        if (aSegment !== bSegment) {
            return (aSegment ?? '').localeCompare(bSegment ?? '');
        }
        return aPosition - bPosition;
    };

    const styleCells = (cell: MutationCell) => {
        if (cell.isReference || cell.value < 0.0001) {
            return {
                style: {
                    ...tableStyle.td,
                    color: 'gray',
                },
            };
        }
        return {};
    };

    const getTableData = (data: Dataset<MutationEntry>, sequenceType: SequenceType) => {
        const basesOfView = bases[sequenceType];
        const mutationsWithoutInsertions = data.content.filter(
            (mutationEntry): mutationEntry is SubstitutionEntry | DeletionEntry => mutationEntry.type !== 'insertion',
        );
        const positionsToProportionAtBase = new Map<string, Map<string, number>>();
        const referenceBases = new Map<string, string>();

        for (const mutationEntry of mutationsWithoutInsertions) {
            const position =
                (mutationEntry.mutation.segment ? `${mutationEntry.mutation.segment}:` : '') +
                mutationEntry.mutation.position;
            referenceBases.set(position, mutationEntry.mutation.valueAtReference);

            const initiallyFillPositionsToProportionAtBase = () => {
                if (!positionsToProportionAtBase.has(position)) {
                    const empty = new Map();
                    basesOfView.forEach((base) => empty.set(base, 0));
                    empty.set(mutationEntry.mutation.valueAtReference, 1);
                    positionsToProportionAtBase.set(position, empty);
                }
            };
            initiallyFillPositionsToProportionAtBase();

            const substitutionValue =
                mutationEntry.type === 'substitution' ? mutationEntry.mutation.substitutionValue : '-';

            const subtractSubstitutionValue = () => {
                const proportionAtBase = positionsToProportionAtBase.get(position)!;
                proportionAtBase.set(substitutionValue, mutationEntry.proportion);
                proportionAtBase.set(
                    mutationEntry.mutation.valueAtReference,
                    proportionAtBase.get(mutationEntry.mutation.valueAtReference)! - mutationEntry.proportion,
                );
            };
            subtractSubstitutionValue();
        }
        const orderedPositionsToProportionAtBase = [...positionsToProportionAtBase.entries()]
            .map(([position, proportionsAtBase]) => ({ position, proportions: proportionsAtBase }))
            .sort((a, b) => {
                return sortPositionsWithSegments(a.position, b.position);
            });

        return orderedPositionsToProportionAtBase.map((proportionsForBaseAtPosition) => {
            return [
                proportionsForBaseAtPosition.position,
                ...bases[sequenceType]
                    .map((base) => {
                        return [
                            proportionsForBaseAtPosition.proportions.get(base)!,
                            { isReference: base === referenceBases.get(proportionsForBaseAtPosition.position) },
                        ];
                    })
                    .flat(),
            ];
        });
    };

    return <Table data={getTableData(data, sequenceType)} columns={getHeaders()} pagination={true} />;
};

export const formatProportion = (proportion: number) => {
    return `${(proportion * 100).toFixed(2)}%`;
};

// lit-components/src/components/mutations-grid.ts
import { customElement, property } from 'lit/decorators.js';
import { css, html, LitElement } from 'lit';
import { Dataset } from '../operator/Dataset';
import { DeletionEntry, MutationEntry, SubstitutionEntry } from '../operator/FetchMutationsOperator';
import { SequenceType } from '../types';
import { bases } from '../mutations';

@customElement('gs-mutations-grid')
export class MutationsGrid extends LitElement {
    static override styles = css`
        table {
            table-layout: fixed;
            border-spacing: 0;
            border-collapse: collapse;
        }
        tr {
            height: 30px;
        }
        th {
            position: sticky;
            top: 0;
            background: white;
        }
        td {
            width: 60px;
            text-align: center;
            border: 1px solid gray;
        }
        td.position {
            width: unset;
            text-align: left;
            padding-right: 25px;
            position: sticky;
            left: 0;
            background: white;
        }
        td.reference {
            color: lightgray;
        }
        td.low {
            color: lightgray;
        }
    `;

    @property()
    data: Dataset<MutationEntry> | null = null;

    @property()
    sequenceType: SequenceType = 'nucleotide';

    override render() {
        if (this.data === null) {
            return html`<div>Error: No data</div>`;
        }
        const bs = bases[this.sequenceType];
        let filtered = this.data.content.filter((d): d is SubstitutionEntry | DeletionEntry => d.type !== 'insertion');
        const grouped = new Map<string, Map<string, number>>();
        const referenceBases = new Map<string, string>();
        for (const d of filtered) {
            const position = (d.mutation.segment ? d.mutation.segment + ':' : '') + d.mutation.position;
            referenceBases.set(position, d.mutation.ref);
            if (!grouped.has(position)) {
                const empty = new Map();
                bs.forEach((b) => empty.set(b, 0));
                empty.set(d.mutation.ref, 1);
                grouped.set(position, empty);
            }
            const group = grouped.get(position)!;
            let alt;
            if (d.type === 'substitution') {
                alt = d.mutation.alt;
            } else {
                alt = '-';
            }
            group.set(alt, d.proportion);
            group.set(d.mutation.ref, group.get(d.mutation.ref)! - d.proportion);
        }
        const ordered = [...grouped.entries()]
            .map(([position, proportions]) => ({ position, proportions }))
            .filter((d) => d.proportions.get(referenceBases.get(d.position)!)! < 0.95)
            .sort((a, b) => {
                const split = (s: string) => {
                    const parts = s.split(':');
                    if (parts.length === 1) {
                        return [undefined, parseInt(parts[0])] as const;
                    } else {
                        return [parts[0], parseInt(parts[1])] as const;
                    }
                };
                const [aSegment, aPosition] = split(a.position);
                const [bSegment, bPosition] = split(b.position);
                if (aSegment !== bSegment) {
                    return (aSegment ?? '').localeCompare(bSegment ?? '');
                }
                return aPosition - bPosition;
            });

        return html`
            <table>
                <thead>
                    <tr>
                        <th class="position">Pos</th>
                        ${bs.map((b) => html`<th>${b}</th>`)}
                    </tr>
                </thead>
                <tbody>
                    ${ordered.map((d) => {
                        return html`<tr>
                            <td class="position">${d.position}</td>
                            ${bs.map(
                                (b) => html` <td
                                    class=${(referenceBases.get(d.position) === b ? 'reference ' : '') +
                                    (d.proportions.get(b)! < 0.0001 ? 'low' : '')}
                                >
                                    ${formatProportion(d.proportions.get(b)!)}
                                </td>`,
                            )}
                        </tr> `;
                    })}
                </tbody>
            </table>
        `;
    }
}

declare global {
    interface HTMLElementTagNameMap {
        'gs-mutations-grid': MutationsGrid;
    }
}

const formatProportion = (proportion: number) => {
    return (proportion * 100).toFixed(2) + '%';
};
