// components/src/preact/mutations/mutations-table.tsx
import { FunctionComponent } from 'preact';
import { Dataset } from '../../operator/Dataset';
import { MutationEntry, MutationType } from '../../operator/FetchMutationsOperator';
import { Table } from '../components/table';
import { TDataObjectRow } from 'gridjs/dist/src/types';
import { formatProportion } from './mutations-grid';

export interface MutationsTableProps {
    data: Dataset<MutationEntry>;
}

const MutationsTable: FunctionComponent<MutationsTableProps> = ({ data }) => {
    const getHeaders = () => {
        return [
            {
                name: 'Mutation',
                sort: true,
            },
            {
                name: 'Type',
                sort: true,
            },
            {
                name: 'Count',
                sort: true,
            },
            {
                name: 'Proportion',
                sort: true,
                formatter: (cell: number) => formatProportion(cell),
            },
        ];
    };

    const getTableData = (data: Dataset<MutationEntry>): TDataObjectRow[] => {
        return data.content.map((mutationEntry): TDataObjectRow => {
            return {
                mutation: mutationEntry.mutation.toString(),
                type: getMutationTypeName(mutationEntry.type),
                count: mutationEntry.count,
                proportion: getProportion(mutationEntry),
            };
        });
    };

    const getMutationTypeName = (mutationType: MutationType) => {
        switch (mutationType) {
            case 'substitution':
                return 'Substitution';
            case 'deletion':
                return 'Deletion';
            case 'insertion':
                return 'Insertion';
            default:
                throw new Error('Invalid mutation type');
        }
    };

    const getProportion = (mutationEntry: MutationEntry) => {
        if (mutationEntry.type === 'insertion') {
            return '';
        }
        return mutationEntry.proportion;
    };

    return <Table data={getTableData(data)} columns={getHeaders()} pagination={true} />;
};

export default MutationsTable;

// lit-components/src/components/mutations-table.ts
import { customElement, property } from 'lit/decorators.js';
import { html, LitElement } from 'lit';
import { Dataset } from '../operator/Dataset';
import { MutationSet } from '../mutations';

@customElement('gs-mutations-table')
export class MutationsTable extends LitElement {
    @property()
    data: Dataset<MutationSet> | null = null;

    override render() {
        if (this.data === null) {
            return html`<div>Error: No data</div>`;
        }

        return html`
            <table>
                <thead>
                    <tr>
                        <th>Mutation</th>
                        <th>Type</th>
                        <th>Count</th>
                        <th>Proportion</th>
                    </tr>
                </thead>
                <tbody>
                    ${this.data.content.map((d) => {
                        const htmlParts = [];
                        htmlParts.push(
                            ...d.substitutions.map(
                                (s) =>
                                    html`<tr>
                                        <td>${s.substitution}</td>
                                        <td>Substitution</td>
                                        <td>${s.count}</td>
                                        <td>${s.proportion}</td>
                                    </tr>`,
                            ),
                        );
                        htmlParts.push(
                            ...d.deletions.map(
                                (s) =>
                                    html`<tr>
                                        <td>${s.deletion}</td>
                                        <td>Deletion</td>
                                        <td>${s.count}</td>
                                        <td>${s.proportion}</td>
                                    </tr>`,
                            ),
                        );
                        htmlParts.push(
                            ...d.insertions.map(
                                (s) =>
                                    html`<tr>
                                        <td>${s.insertion}</td>
                                        <td>Insertion</td>
                                        <td>${s.count}</td>
                                        <td></td>
                                    </tr>`,
                            ),
                        );
                        return htmlParts;
                    })}
                </tbody>
            </table>
        `;
    }
}

declare global {
    interface HTMLElementTagNameMap {
        'gs-mutations-table': MutationsTable;
    }
}
