// lit-components/src/components/relative-growth-advantage-chart.ts
import { customElement, property } from 'lit/decorators.js';
import { html, LitElement } from 'lit';
import { Chart, registerables } from 'chart.js';

@customElement('gs-relative-growth-advantage-chart')
export class RelativeGrowthAdvantageChart extends LitElement {
    @property()
    data: {
        t: string[];
        proportion: number[];
        ciLower: number[];
        ciUpper: number[];
        observed: number[];
    } = {
        t: [],
        proportion: [],
        ciLower: [],
        ciUpper: [],
        observed: [],
    };

    override firstUpdated() {
        const ctx = this.renderRoot.querySelector('canvas')!.getContext('2d')!;
        Chart.register(...registerables);
        new Chart(ctx, {
            data: {
                labels: this.data.t,
                datasets: [
                    {
                        type: 'line',
                        label: 'Prevalence',
                        data: this.data.proportion,
                        borderWidth: 1,
                        pointRadius: 0,
                    },
                    {
                        type: 'line',
                        label: 'CI Lower',
                        data: this.data.ciLower,
                        borderWidth: 1,
                        pointRadius: 0,
                    },
                    {
                        type: 'line',
                        label: 'CI Upper',
                        data: this.data.ciUpper,
                        borderWidth: 1,
                        pointRadius: 0,
                    },
                    {
                        type: 'scatter',
                        label: 'Observed',
                        data: this.data.observed,
                        pointRadius: 1,
                    },
                ],
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true,
                    },
                },
                plugins: {
                    legend: {
                        display: false,
                    },
                    tooltip: {
                        mode: 'index',
                        intersect: false,
                    },
                },
            },
        });
    }

    override render() {
        return html`
            <div>
                <canvas></canvas>
            </div>
        `;
    }
}

declare global {
    interface HTMLElementTagNameMap {
        'gs-relative-growth-advantage-chart': RelativeGrowthAdvantageChart;
    }
}

// components/src/preact/relativeGrowthAdvantage/relative-growth-advantage-chart.tsx
import { Chart, type ChartConfiguration, registerables } from 'chart.js';

import { type YearMonthDay } from '../../utils/temporal';
import GsChart from '../components/chart';
import { LogitScale } from '../shared/charts/LogitScale';
import { getYAxisScale, type ScaleType } from '../shared/charts/getYAxisScale';

interface RelativeGrowthAdvantageChartData {
    t: YearMonthDay[];
    proportion: number[];
    ciLower: number[];
    ciUpper: number[];
    observed: number[];
}

interface RelativeGrowthAdvantageChartProps {
    data: RelativeGrowthAdvantageChartData;
    yAxisScaleType: ScaleType;
}

Chart.register(...registerables, LogitScale);

const RelativeGrowthAdvantageChart = ({ data, yAxisScaleType }: RelativeGrowthAdvantageChartProps) => {
    const config: ChartConfiguration = {
        type: 'line',
        data: {
            labels: data.t,
            datasets: [
                {
                    type: 'line',
                    label: 'Prevalence',
                    data: data.proportion,
                    borderWidth: 1,
                    pointRadius: 0,
                },
                {
                    type: 'line',
                    label: 'CI Lower',
                    data: data.ciLower,
                    borderWidth: 1,
                    pointRadius: 0,
                },
                {
                    type: 'line',
                    label: 'CI Upper',
                    data: data.ciUpper,
                    borderWidth: 1,
                    pointRadius: 0,
                },
                {
                    type: 'scatter',
                    label: 'Observed',
                    data: data.observed,
                    pointRadius: 1,
                },
            ],
        },
        options: {
            animation: false,
            scales: {
                y: getYAxisScale(yAxisScaleType),
            },
            plugins: {
                legend: {
                    display: false,
                },
                tooltip: {
                    mode: 'index',
                    intersect: false,
                },
            },
        },
    };

    return <GsChart configuration={config} />;
};

export default RelativeGrowthAdvantageChart;
