// lit-components/src/components/relative-growth-advantage.ts
import { html, LitElement } from 'lit';
import { customElement, property } from 'lit/decorators.js';
import { Task } from '@lit/task';
import './component-container';
import './relative-growth-advantage-chart';
import { type LapisFilter } from '../types';
import { lapisContext } from '../lapis-context';
import { consume } from '@lit/context';
import { queryRelativeGrowthAdvantage } from '../query/queryRelativeGrowthAdvantage';

type View = 'line';

export type RelativeGrowthAdvantageProps = {
    numerator: LapisFilter;
    denominator: LapisFilter;
    generationTime: number;
    views: View[];
};

@customElement('gs-relative-growth-advantage')
export class RelativeGrowthAdvantage extends LitElement {
    @consume({ context: lapisContext })
    lapis: string = '';

    @property({ type: Object })
    numerator: LapisFilter = {};

    @property({ type: Object })
    denominator: LapisFilter = {};

    @property({ type: Number })
    generationTime: number = 7;

    @property({ type: Object })
    views: View[] = ['line'];

    private fetchingTask = new Task(this, {
        task: async ([lapis, numerator, denominator, generationTime], { signal }) => {
            return await queryRelativeGrowthAdvantage(numerator, denominator, generationTime, lapis, signal);
        },
        args: () => [this.lapis, this.numerator, this.denominator, this.generationTime, this.views] as const,
    });

    override render() {
        return this.fetchingTask.render({
            pending: () => html`
                <h1>Relative growth advantage</h1>
                Loading...
            `,
            complete: (data) => html`
                <h1>Relative growth advantage</h1>

                <gs-component-container>
                    >${this.views.map(
                        (view, index) => html`
                            ${view === 'line'
                                ? html`<gs-component-tab slot="content" title="Line chart" .active="${index === 0}">
                                          <gs-relative-growth-advantage-chart
                                              .data=${{
                                                  ...data.estimatedProportions,
                                                  observed: data.observedProportions,
                                              }}
                                              type="bar"
                                          ></gs-relative-growth-advantage-chart>
                                          <div>
                                              Advantage: ${(data.params.fd.value * 100).toFixed(2)}%
                                              (${(data.params.fd.ciLower * 100).toFixed(2)}% -
                                              ${(data.params.fd.ciUpper * 100).toFixed(2)}%)
                                          </div>
                                      </gs-component-tab>
                                      <gs-component-toolbar slot="toolbar" .active="${index === 0}">
                                      </gs-component-toolbar>
                                      <gs-component-info slot="info"> TODO </gs-component-info> `
                                : ''}
                        `,
                    )}
                </gs-component-container>
            `,
            error: (e) => html`<p>Error: ${e}</p>`,
        });
    }
}

declare global {
    interface HTMLElementTagNameMap {
        'gs-relative-growth-advantage': RelativeGrowthAdvantage;
    }
}

// components/src/preact/relativeGrowthAdvantage/relative-growth-advantage.tsx
import { type FunctionComponent } from 'preact';
import { useContext, useState } from 'preact/hooks';

import RelativeGrowthAdvantageChart from './relative-growth-advantage-chart';
import {
    queryRelativeGrowthAdvantage,
    type RelativeGrowthAdvantageData,
} from '../../query/queryRelativeGrowthAdvantage';
import { type LapisFilter } from '../../types';
import { LapisUrlContext } from '../LapisUrlContext';
import { ErrorDisplay } from '../components/error-display';
import Headline from '../components/headline';
import Info from '../components/info';
import { LoadingDisplay } from '../components/loading-display';
import { NoDataDisplay } from '../components/no-data-display';
import { ResizeContainer, type Size } from '../components/resize-container';
import { ScalingSelector } from '../components/scaling-selector';
import Tabs from '../components/tabs';
import { type ScaleType } from '../shared/charts/getYAxisScale';
import { useQuery } from '../useQuery';

export type View = 'line';

export interface RelativeGrowthAdvantageProps {
    numerator: LapisFilter;
    denominator: LapisFilter;
    generationTime: number;
    views: View[];
    size?: Size;
}

export const RelativeGrowthAdvantage: FunctionComponent<RelativeGrowthAdvantageProps> = ({
    numerator,
    denominator,
    generationTime,
    views,
    size,
}) => {
    const lapis = useContext(LapisUrlContext);
    const [yAxisScaleType, setYAxisScaleType] = useState<ScaleType>('linear');

    const { data, error, isLoading } = useQuery(
        () => queryRelativeGrowthAdvantage(numerator, denominator, generationTime, lapis),
        [lapis, numerator, denominator, generationTime, views],
    );

    const headline = 'Relative growth advantage';
    if (isLoading) {
        return (
            <Headline heading={headline}>
                <LoadingDisplay />
            </Headline>
        );
    }

    if (error !== null) {
        return (
            <Headline heading={headline}>
                <ErrorDisplay error={error} />
            </Headline>
        );
    }

    if (data === null) {
        return (
            <Headline heading={headline}>
                <NoDataDisplay />
            </Headline>
        );
    }

    return (
        <ResizeContainer size={size} defaultSize={{ height: '700px', width: '100%' }}>
            <Headline heading={headline}>
                <RelativeGrowthAdvantageTabs
                    data={data}
                    yAxisScaleType={yAxisScaleType}
                    setYAxisScaleType={setYAxisScaleType}
                    views={views}
                />
            </Headline>
        </ResizeContainer>
    );
};

type RelativeGrowthAdvantageTabsProps = {
    data: NonNullable<RelativeGrowthAdvantageData>;
    yAxisScaleType: ScaleType;
    setYAxisScaleType: (scaleType: ScaleType) => void;
    views: View[];
};

const RelativeGrowthAdvantageTabs: FunctionComponent<RelativeGrowthAdvantageTabsProps> = ({
    data,
    yAxisScaleType,
    setYAxisScaleType,
    views,
}) => {
    const getTab = (view: View) => {
        switch (view) {
            case 'line':
                return {
                    title: 'Line',
                    content: (
                        <RelativeGrowthAdvantageChart
                            data={{
                                ...data.estimatedProportions,
                                observed: data.observedProportions,
                                params: data.params,
                            }}
                            yAxisScaleType={yAxisScaleType}
                        />
                    ),
                };
        }
    };

    const tabs = views.map((view) => getTab(view));
    const toolbar = () => (
        <RelativeGrowthAdvantageToolbar yAxisScaleType={yAxisScaleType} setYAxisScaleType={setYAxisScaleType} />
    );

    return <Tabs tabs={tabs} toolbar={toolbar} />;
};

type RelativeGrowthAdvantageToolbarProps = {
    yAxisScaleType: ScaleType;
    setYAxisScaleType: (scaleType: ScaleType) => void;
};

const RelativeGrowthAdvantageToolbar: FunctionComponent<RelativeGrowthAdvantageToolbarProps> = ({
    yAxisScaleType,
    setYAxisScaleType,
}) => {
    return (
        <div class='flex'>
            <ScalingSelector yAxisScaleType={yAxisScaleType} setYAxisScaleType={setYAxisScaleType} />
            <Info className='ml-1' content='Line chart' />
        </div>
    );
};
